name: 'Firefox: reference string linter'
permissions: read-all
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'focus-ios/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'focus-ios/**'
  workflow_dispatch:

jobs:
  check:
    runs-on: macos-26
    strategy:
      matrix:
        xcode: ["26.2"]
        python-version: ["3.12"]
        node-version: ["24"]
    steps:
      - name: Clone code repository
        uses: actions/checkout@v6
        with:
          path: "code_repo"
      - name: Clone l10n repository
        uses: actions/checkout@v6
        with:
          repository: "mozilla-l10n/firefoxios-l10n"
          path: "l10n_repo"
      - name: Select Xcode ${{ matrix.xcode }}
        run: |
          sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install l10n dependencies
        run: |
          pip install -r l10n_repo/.github/scripts/requirements.txt
      - name: Run bootstrap script
        run: |
          cd code_repo
          sh ./bootstrap.sh
      - name: Extract strings
        run: |
          start_folder="$PWD"

          # Clone localization tools
          git clone https://github.com/mozilla-mobile/LocalizationTools --depth 1

          # Extract strings
          cd LocalizationTools
          swift run LocalizationTools --export --project-path "${start_folder}/code_repo/firefox-ios/Client.xcodeproj" --l10n-project-path "${start_folder}/l10n_repo" --locale en-US
      - name: Check reference locale
        run: |
          (cd code_repo && moz-xliff-lint --path ../l10n_repo/en-US --config .github/l10n/linter_config_ios.json)
      - name: Store reference artifact
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: firefox-xliff-file
          path: l10n_repo/en-US/*.xliff
          if-no-files-found: ignore
